### ISSUE TITLE
Error while fetching the boilerplate

### ISSUE THREAD

**Issue by schemogroby** [weslly/Nettuts-Fetch#13]
Console Error when fetching the "predefined" html5boilerplate.
This issue occurs on my mac os x as well as on my win pc (both behind the same proxy)

On the other hand, fetching the "predefined" single jquery file works.

<pre>
Traceback (most recent call last):
  File ".\Fetch.py", line 107, in get_package
AttributeError: 'NoneType' object has no attribute 'run_command'
</pre>

**Comment by weslly** [comment]
Probably this is a problem with your proxy/firewall, like #9. Have you tried it with another network? Btw, make sure your proxy don't block `.zip` files.

**Comment by schemogroby** [comment]
Sorry for the hassle, seems to be gone now (kind of a temporary error) - now it works without any changes

**Comment by jirivrany** [comment]
I use to have the same problem.  The reason is not in the proxy/network settings. This error ocures, when you have no active tab opened. In this cas self.window.active_view() is NoneType and this raises AttributeError exception.

**Comment by kblomqvist** [comment]
Yeah I have seen this also. How about using

```
self.window.run_command()
```

instead of

```
self.window.active_view().run_command()
```

**Comment by weslly** [comment]
Good catch, @jirivrany. This is a small regression created with 45e88e6f0a24b60067bf9bac06b7c0d445b321df.

**Comment by jirivrany** [comment]
@kblomqvist - Yes, that solution is even better than my Try: Except. It works fine without error.
