### ISSUE TITLE
Can't make the fetch util to download one file

### ISSUE THREAD

**Issue by huglester** [weslly/Nettuts-Fetch#21]
Hello,

Fetch method works for me for several urls.
But when I try to fetch this: https://raw.github.com/carhartl/jquery-cookie/master/jquery.cookie.js it simply won't show up in my editor.. but I see h message 'Downloading'...

any ideas someone? 

Thank you

**Comment by weslly** [comment]
Are you using ST3?

**Comment by huglester** [comment]
Sorry I did not write about it. I'm on Windows 8 x64, version is ST2 ...

Thank you

**Comment by weslly** [comment]
Can you see if are there any errors in ST's console when you try to download the file?

**Comment by huglester** [comment]
Hello strange I'm not receiveing emails about this topic updates :(

Here is the error I tracked in: 

Exception in thread Thread-424:
Traceback (most recent call last):
  File ".\threading.py", line 532, in __bootstrap_inner
  File ".\Fetch.py", line 210, in run
  File ".\Fetch.py", line 221, in download_text
UnicodeDecodeError: 'utf8' codec can't decode byte 0x8b in position 1: unexpected code byte

**Comment by dvnguyen** [comment]
I'm not sure if this is related but I'm also having similar issue when trying to download the less.js file from https://raw.github.com/less/less.js/master/dist/less-1.6.0.min.js within ST2.

I'm getting the following output in the console:
    Exception in thread Thread-63:
    Traceback (most recent call last):
      File ".\threading.py", line 532, in __bootstrap_inner
      File "./fetch/downloader.py", line 44, in run
      File "./fetch/downloader.py", line 95, in download_text
    AttributeError: 'URLError' object has no attribute 'code'

**Comment by buildersbrewery** [comment]
@huglester you had a typo in the URL, `https://raw.githubusercontent.com/carhartl/jquery-cookie/master/cookie.jquery.json` works fine for me

@dvnguyen same for you, fixing the typo and testing `https://raw.githubusercontent.com/less/less.js/master/dist/less.min.js` worked fine for me

---

please close issue

**Comment by huglester** [comment]
I am not sure... did not use this functionality in a meantimw. If it will not work in the future. If it will not work I will resubmit.
