### ISSUE TITLE
Downloaded files apear in new file in st3

### ISSUE THREAD

**Issue by huglester** [weslly/Nettuts-Fetch#27]
Hello

I use st3 branch, and downloaded  files are opened in the new tab. 
Maybe there is possibility for downloaded source to appear right away inside the file?
So I can fetch jquery, jquery cycle and something else to one file.

I think it was default behaviour in st2.

Maybe even better to make it a configurable?

Thank you

**Comment by tadaszelvys** [comment]
That would be great :+1:

**Comment by weslly** [comment]
fixed in v2.0 release
