### ISSUE TITLE
Package Control can't find Fetch packages.json file...

### ISSUE THREAD

**Issue by bmcminn** [weslly/Nettuts-Fetch#40]
https://sublime.wbond.net/packages/Nettuts%2B%20Fetch

The wbond crawler can't find the packages.json file, which prevents the Package Control plugin from being able to list and install it.

Tried in ST2 and ST3, consistent issue where I cannot find the package from inside Sublime Text.

**Comment by weslly** [comment]
It was an issue with Package Control itself (which seems to be already fixed by now).
