### ISSUE TITLE
Fetch can not extract package from Bitbucket

### ISSUE THREAD

**Issue by vvincent** [weslly/Nettuts-Fetch#5]
Fetch can not pull unzip file from bittbucket. I received the following error:

"Fetch: Unable to extract package due to unsafe filename on one or more files."

The zip folder does contains a .DS_Store file

**Comment by weslly** [comment]
Can you post the link (if it's public, of course) for the zip file you're trying to fetch?

**Comment by vvincent** [comment]
https://bitbucket.org/vvincent/express-boilerplate/get/d9b5b56e09bc.zip

**Comment by weslly** [comment]
Thanks for the link, the problem is with this file in your zip package:

```
vvincent-express-boilerplate-d9b5b56e09bc/web/node_modules/express/node_modules/connect/node_modules/formidable/..travis.yml.un~
```

There is a known security issue with files that have two dots in their name. You can learn about it at  http://docs.python.org/library/zipfile.html#zipfile.ZipFile.extractall and http://stackoverflow.com/a/641100/454598

**Comment by vvincent** [comment]
Thank you for your help. I will delete this file. Great work.
